# Generated by Django 5.0.7 on 2024-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_date', models.DateField()),
                ('picture', models.ImageField(upload_to='member_pictures/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Non Active', 'Non Active')], default='Active', max_length=10)),
            ],
        ),
    ]
