# Generated by Django 5.0.7 on 2024-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('Not paid', 'Not paid')], default='Active', max_length=10),
        ),
    ]
